/* AI recipe generation (Fix 3) and budget-based dinner suggestions (Fix 4).
   Generated recipes always pass through the editable review editor before
   saving, and behave like any other recipe afterwards (cook mode included). */

import { dbAll } from '../db.js';
import { el, openSheet, toast } from '../ui.js';
import { generateRecipe, getApiKey, setApiKey } from '../ai.js';
import { analyzeRecipe, preferenceScore } from '../recommend.js';
import { recipeCost, fmtMoney } from '../cost.js';
import { openRecipeEditor } from './recipeedit.js';
import { openRecipeDetail } from './recipes.js';

const SPARKLE_ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3zM19 15l.9 2.6L22.5 18l-2.6.9L19 21.5l-.9-2.6L15.5 18l2.6-.9L19 15z"/></svg>';

/* ── Fix 3: generate a recipe ── */

export function openGenerateSheet({ onSaved, craving = '', budget = null } = {}) {
  openSheet({
    title: 'Generate a recipe',
    async build(body, api) {
      const key = await getApiKey();
      body.innerHTML = '';
      if (!key) renderKeySetup(body, () => openAfterKey(api, { onSaved, craving, budget }));
      else renderGenerateForm(body, api, { onSaved, craving, budget });
    },
  });
}

function openAfterKey(api, opts) {
  api.close();
  openGenerateSheet(opts);
}

function renderKeySetup(body, onDone) {
  const input = el('input', {
    class: 'field-input', type: 'password', autocomplete: 'off',
    placeholder: 'sk-ant-…',
  });
  body.append(
    el('p', { class: 'confirm-msg' },
      'Recipe generation uses Claude via your own Anthropic API key. The key is stored only on this device. Create one at ',
      el('a', { href: 'https://console.anthropic.com/settings/keys', target: '_blank', rel: 'noopener', class: 'r-source' }, 'console.anthropic.com'),
      ' — a workspace-scoped key with a small spend limit is a good idea.'),
    el('div', { class: 'form-label' }, 'Anthropic API key'),
    input,
    el('div', { class: 'sheet-actions' },
      el('button', {
        class: 'btn btn-primary',
        onclick: async () => {
          const value = input.value.trim();
          if (!value) { input.focus(); return; }
          await setApiKey(value);
          onDone();
        },
      }, 'Save & continue')
    )
  );
  setTimeout(() => input.focus(), 120);
}

function renderGenerateForm(body, api, { onSaved, craving, budget }) {
  const cravingInput = el('input', {
    class: 'field-input', type: 'text', autocomplete: 'off',
    placeholder: 'e.g. something creamy with chicken', value: craving,
  });

  let serves = 2;
  const servesInput = el('input', { class: 'qty-input', type: 'text', inputmode: 'numeric', value: '2' });
  const stepper = el('div', { class: 'stepper' },
    el('button', { onclick: () => { serves = Math.max(1, (parseInt(servesInput.value, 10) || serves) - 1); servesInput.value = String(serves); } }, '−'),
    servesInput,
    el('button', { onclick: () => { serves = (parseInt(servesInput.value, 10) || serves) + 1; servesInput.value = String(serves); } }, '+')
  );

  const budgetInput = el('input', {
    class: 'field-input', type: 'text', inputmode: 'decimal',
    placeholder: 'optional', value: budget != null ? String(budget) : '',
  });

  const status = el('div', { class: 'form-hint' });
  const err = el('div', { class: 'form-hint form-warn' });
  const generateBtn = el('button', { class: 'btn btn-primary' }, 'Generate');

  generateBtn.addEventListener('click', async () => {
    err.textContent = '';
    generateBtn.disabled = true;
    status.textContent = 'Asking Claude — this takes a little while…';
    const b = parseFloat(String(budgetInput.value).replace(',', '.').replace('$', ''));
    const result = await generateRecipe({
      craving: cravingInput.value.trim(),
      serves: Math.max(1, parseInt(servesInput.value, 10) || 2),
      budget: Number.isFinite(b) && b > 0 ? Math.round(b * 100) / 100 : null,
    });
    generateBtn.disabled = false;
    status.textContent = '';
    if (result.status === 'ok') {
      api.close();
      openRecipeEditor(result.recipe, {
        onSaved,
        extracted: true,
        bannerText: 'Generated by Claude around your pantry — check quantities and steps before saving.',
      });
      return;
    }
    if (result.status === 'nokey' || result.status === 'auth') {
      if (result.status === 'auth') await setApiKey(null);
      err.textContent = result.message || 'API key needed.';
      body.innerHTML = '';
      renderKeySetup(body, () => openAfterKey(api, { onSaved, craving: cravingInput.value, budget }));
      return;
    }
    err.textContent = result.message || 'Something went wrong — try again.';
  });

  body.append(
    el('div', { class: 'form-label' }, 'What are you in the mood for?'),
    cravingInput,
    el('div', { class: 'form-label' }, 'Serves'),
    el('div', { class: 'qty-row' }, stepper),
    el('div', { class: 'form-label' }, 'Budget for missing ingredients ($)'),
    budgetInput,
    el('div', { class: 'form-hint' }, 'Claude builds around your pantry and the recipes you’ve liked or cooked.'),
    status, err,
    el('div', { class: 'sheet-actions' }, generateBtn),
    el('button', {
      class: 'disclosure',
      onclick: async () => { await setApiKey(null); body.innerHTML = ''; renderKeySetup(body, () => openAfterKey(api, { onSaved, craving: cravingInput.value, budget })); },
    }, 'Change API key')
  );
  setTimeout(() => cravingInput.focus(), 120);
}

/* ── Fix 4: dinner on a budget ── */

export function openBudgetDinner({ onSaved } = {}) {
  openSheet({
    title: 'Dinner on a budget',
    build(body, api) {
      const input = el('input', {
        class: 'field-input', type: 'text', inputmode: 'decimal', placeholder: 'e.g. 15',
      });
      const results = el('div', { class: 'off-results' });

      async function suggest() {
        const b = parseFloat(String(input.value).replace(',', '.').replace('$', ''));
        const budget = Number.isFinite(b) && b > 0 ? Math.round(b * 100) / 100 : null;
        if (budget == null) { input.focus(); return; }
        results.innerHTML = '';

        const [recipes, pantryAll] = await Promise.all([dbAll('recipes'), dbAll('pantry')]);
        const pantry = pantryAll.filter((p) => p.quantity.amount > 0);
        const scored = recipes.map((r) => ({
          r,
          a: analyzeRecipe(r, pantry),
          c: recipeCost(r, pantry),
        })).sort((x, y) =>
          x.a.missing.length - y.a.missing.length
          || (x.c.total ?? Infinity) - (y.c.total ?? Infinity)
          || preferenceScore(y.r) - preferenceScore(x.r));

        if (scored.length) {
          results.append(el('div', { class: 'form-label' }, 'From your recipes — fewest to buy first'));
          const card = el('div', { class: 'card' });
          for (const { r, a, c } of scored.slice(0, 6)) {
            const meta = [`have ${a.have}/${a.total}`];
            if (c.perServe != null) meta.push(`~${fmtMoney(c.perServe)}/serve from pantry`);
            card.append(
              el('button', { class: 'row', onclick: () => { api.close(); openRecipeDetail(r.id); } },
                el('div', { class: 'row-main' },
                  el('div', { class: 'row-name' }, r.title),
                  el('div', { class: 'row-meta' }, meta.join(' · '))),
                el('span', { class: `match-chip${a.missing.length === 0 ? ' ok' : a.missing.length <= 2 ? ' near' : ''}` },
                  a.missing.length === 0 ? '$0 to buy' : `${a.missing.length} to buy`)
              )
            );
          }
          results.append(card);
          results.append(el('div', { class: 'form-hint' },
            'Larder can’t price items you haven’t bought yet, so saved recipes are ranked by how little needs buying.'));
        } else {
          results.append(el('div', { class: 'form-hint' }, 'No saved recipes yet — generate one below.'));
        }

        results.append(
          el('button', {
            class: 'btn-scan', style: 'margin-top:14px',
            onclick: () => { api.close(); openGenerateSheet({ onSaved, budget }); },
          }, el('span', { html: SPARKLE_ICON }), `Generate a new idea under ${fmtMoney(budget)}`)
        );
      }

      body.append(
        el('div', { class: 'form-label' }, 'What do you want to spend on dinner? ($)'),
        el('div', { class: 'fetch-row' },
          input,
          el('button', { class: 'btn btn-primary fetch-btn', onclick: suggest }, 'Suggest')),
        results
      );
      setTimeout(() => input.focus(), 120);
    },
  });
}
